SELECT * FROM tbproduto;

SELECT CPF, NOME FROM tbcliente;

SELECT CPF FROM tbcliente LIMIT 5; 

SELECT CPF AS CPF_CLIENTE, NOME AS NOME_CLIENTE FROM tbcliente;

SELECT NOME, SEXO, CPF FROM tbcliente;